### ISSUE TITLE
Better Describe Purpose of Root Modules

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-root-modules#52]
## what
* these are examples of how we've implemented various *common* patterns with our customers
* the root modules are the *most opinionated* incarnations of modules that seldom translate *verbatim* across organizations.  This is your secret sauce. We could never implement this in a generic way without creating crazy bloat. The `terraform-root-modules` is your “starting off point” where you hardfork/diverge. These modules are very specific to how we do things in our environment, so they might not "drop in" smoothly in other environments as they make a lot of assumptions on how things are organized.
* this is where you start now with your clean `terraform-root-module` repo and start to create a new project there in to describe the infrastructure that you want.
* no 2 companies will ever have the same `terraform-root-modules`
* root modules *never compose* other root modules. If or when this is desired, then the composite module should be split of into a new repository and versioned independently
* root modules become the module catalog of *your organization* that developers choose from
* a company writes their own root modules. it’s your flavor of how to leverage the generic building blocks to achieve the specific customizations that you need without needing to write everything from the ground up because your leveraging our general modules. the idea is to write all `terraform-aws*` modules very generically
* These `terraform-root-modules` are not strictly part of geodesic, but they can be used together with it. 
* Every root module should include a `Makefile` that defines `init`, `plan`, `apply`. This establishes a common interface for interacting with terraform without the need of `terragrunt`

Update description to mention: 

Normally, a company should build up a service catalog of terraform modules, which is just a collection of terraform modules that capture the opinions, best practices and non-functional requirements of that organization.

## for example

> in the case where I have a pre-production account that has like 30+ vpcs?

This is where you probably treat those as separate projects in your company's own `terraform-root-modules`. Each VPC might have their own TF state.

**Comment by jdn-za** [comment]
Brilliant thanks that clears things up nicely

**Comment by osterman** [comment]
Let's also add this to the quick start so we better call out the purpose of root modules.
